title: "Toca Raul! Podcast"
url: "http://toca.raulhc.cc"
description: "Toca Raul! Podcast, o podcast do Raul Hacker Club"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:title
ins_logo: "/images/pixel.png"
favicon: "/images/pixel.png"

footer: yes
footer_url: "./sobre/"
footer_text: "Feito com <3 pelo e no Raul Hacker Club"

paginate: 20
paginate_path: "/:num"
plugins: [jekyll-paginate]

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Categorias"
   link: "/categorias"
 - name: "Feed"
   link: "/feeds"
 - name: "Sobre"
   link: "/sobre"
